




CREATE TABLE Profession (

 primaryKey UUID NOT NULL,

 Name VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE ServiceRequest (

 primaryKey UUID NOT NULL,

 Type VARCHAR(13) NULL,

 Number INT NULL,

 Date TIMESTAMP(3) NULL,

 Status VARCHAR(9) NULL,

 PermanentAddress VARCHAR(255) NULL,

 PhoneNumber VARCHAR(255) NULL,

 INN VARCHAR(255) NULL,

 ServiceRequestDecision VARCHAR(9) NULL,

 DecisionDate TIMESTAMP(3) NULL,

 ProfessionD UUID NOT NULL,

 Passport UUID NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE Patent (

 primaryKey UUID NOT NULL,

 Series VARCHAR(255) NULL,

 ValidUntil TIMESTAMP(3) NULL,

 Number VARCHAR(255) NULL,

 IssueDate TIMESTAMP(3) NULL,

 Profession_m0 UUID NOT NULL,

 ServiceRequest_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE Passport (

 primaryKey UUID NOT NULL,

 FirstNameLat VARCHAR(255) NULL,

 LastNameLat VARCHAR(255) NULL,

 SecondNameLat VARCHAR(255) NULL,

 Sex VARCHAR(255) NULL,

 DateOfBirth TIMESTAMP(3) NULL,

 PlaceOfBirth VARCHAR(255) NULL,

 DateOfIssue TIMESTAMP(3) NULL,

 ValidUntil TIMESTAMP(3) NULL,

 NumberSeries VARCHAR(255) NULL,

 Country VARCHAR(5) NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMNETLOCKDATA (

 LockKey VARCHAR(300) NOT NULL,

 UserName VARCHAR(300) NOT NULL,

 LockDate TIMESTAMP(3) NULL,

 PRIMARY KEY (LockKey));



CREATE TABLE STORMSETTINGS (

 primaryKey UUID NOT NULL,

 Module VARCHAR(1000) NULL,

 Name VARCHAR(255) NULL,

 Value TEXT NULL,

 "User" VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMAdvLimit (

 primaryKey UUID NOT NULL,

 "User" VARCHAR(255) NULL,

 Published BOOLEAN NULL,

 Module VARCHAR(255) NULL,

 Name VARCHAR(255) NULL,

 Value TEXT NULL,

 HotKeyData INT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMFILTERSETTING (

 primaryKey UUID NOT NULL,

 Name VARCHAR(255) NOT NULL,

 DataObjectView VARCHAR(255) NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMWEBSEARCH (

 primaryKey UUID NOT NULL,

 Name VARCHAR(255) NOT NULL,

 "Order" INT NOT NULL,

 PresentView VARCHAR(255) NOT NULL,

 DetailedView VARCHAR(255) NOT NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMFILTERDETAIL (

 primaryKey UUID NOT NULL,

 Caption VARCHAR(255) NOT NULL,

 DataObjectView VARCHAR(255) NOT NULL,

 ConnectMasterProp VARCHAR(255) NOT NULL,

 OwnerConnectProp VARCHAR(255) NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE STORMFILTERLOOKUP (

 primaryKey UUID NOT NULL,

 DataObjectType VARCHAR(255) NOT NULL,

 Container VARCHAR(255) NULL,

 ContainerTag VARCHAR(255) NULL,

 FieldsToView VARCHAR(255) NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE UserSetting (

 primaryKey UUID NOT NULL,

 AppName VARCHAR(256) NULL,

 UserName VARCHAR(512) NULL,

 UserGuid UUID NULL,

 ModuleName VARCHAR(1024) NULL,

 ModuleGuid UUID NULL,

 SettName VARCHAR(256) NULL,

 SettGuid UUID NULL,

 SettLastAccessTime TIMESTAMP(3) NULL,

 StrVal VARCHAR(256) NULL,

 TxtVal TEXT NULL,

 IntVal INT NULL,

 BoolVal BOOLEAN NULL,

 GuidVal UUID NULL,

 DecimalVal DECIMAL(20,10) NULL,

 DateTimeVal TIMESTAMP(3) NULL,

 PRIMARY KEY (primaryKey));



CREATE TABLE ApplicationLog (

 primaryKey UUID NOT NULL,

 Category VARCHAR(64) NULL,

 EventId INT NULL,

 Priority INT NULL,

 Severity VARCHAR(32) NULL,

 Title VARCHAR(256) NULL,

 Timestamp TIMESTAMP(3) NULL,

 MachineName VARCHAR(32) NULL,

 AppDomainName VARCHAR(512) NULL,

 ProcessId VARCHAR(256) NULL,

 ProcessName VARCHAR(512) NULL,

 ThreadName VARCHAR(512) NULL,

 Win32ThreadId VARCHAR(128) NULL,

 Message VARCHAR(2500) NULL,

 FormattedMessage TEXT NULL,

 PRIMARY KEY (primaryKey));




 ALTER TABLE ServiceRequest ADD CONSTRAINT FK3ed3c48868d84640816505dcbc91e762 FOREIGN KEY (ProfessionD) REFERENCES Profession; 
CREATE INDEX Index9340c693ca87b7324270e95ba08d12b67586724a on ServiceRequest (ProfessionD); 

 ALTER TABLE ServiceRequest ADD CONSTRAINT FK11da0cb0e1a34365b782dc3ed0b9990f FOREIGN KEY (Passport) REFERENCES Passport; 
CREATE INDEX Indexb69b262ba46cd2d427c91531916fee90beb21fef on ServiceRequest (Passport); 

 ALTER TABLE Patent ADD CONSTRAINT FKb9af3fc4691247059178c5f20eb33b5b FOREIGN KEY (Profession_m0) REFERENCES Profession; 
CREATE INDEX Indexc9d86e9eaebe2f99ea31416b0e16d11e5f68b910 on Patent (Profession_m0); 

 ALTER TABLE Patent ADD CONSTRAINT FKff4d445472d34616a65e51395ec01a32 FOREIGN KEY (ServiceRequest_m0) REFERENCES ServiceRequest; 
CREATE INDEX Indexf210ce07061ccca1dc62c60612930660f7da61ac on Patent (ServiceRequest_m0); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc864a04f0fde4c9d9ebb70b7e5c99e2d FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK167927a52ddb4617ae453e93b6dc56a9 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKaff85f31bad34c49b192871d23eb19c1 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

